CREATE TABLE Request (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  body VARCHAR(250) NOT NULL,
  detail VARCHAR(250) NULL,
  status VARCHAR(250) NULL,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated DATETIME,

  unique (body)
);